{% set name = "forcefield-utilities" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mosdef-hub/forcefield-utilities/archive/{{ version }}.tar.gz
  sha256: 772f696f493354ed5b7436baf64cff8878d18b9c91fc7ad0621bb519522e8ba7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - foyer
    - gmso >=0.9.0
    - pydantic
    - lxml

test:
  imports:
    - forcefield_utilities
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mosdef-hub/forcefield-utilities
  summary: Utility functions and classes necessary to convert xml forcefields to foyer and gmso Forcefields
  description: |
    Utility functions and classes necessary to convert xml forcefields to foyer and gmso Forcefields
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/mosdef-hub/forcefield-utilities
  dev_url: https://github.com/mosdef-hub/forcefield-utilities

extra:
  recipe-maintainers:
    - umesh-timalsina
    - CalCraven
    - justinGilmer
    - daico007
